### ISSUE TITLE
[Heroku] Admin access to repository required

### ISSUE THREAD

**Issue by GQMai** [ARMmbed/pelion-quick-start-web-app#13]
Hi,

When I am trying to deploy this repo on Heroku, it shows ‘Admin access to repository required’.
I need to fork this to my repo.
Thanks.

![image](https://user-images.githubusercontent.com/5309276/75222684-b8ebb500-57df-11ea-980f-4206b332fc91.png)

**Comment by froeba** [comment]
Hi,

Did you get this message:
* by clicking the Heroku button on the README
or
* by trying to link the Github Account for auto deployment?

I think that linking to the repo would require Admin access, but the one-time clone does not.

**Comment by GQMai** [comment]
Hi,
I got this when I tried to connect to this Github repo in Heroku. But I find the app actually starts up successfully.
Maybe it's not a problem.
![image](https://user-images.githubusercontent.com/5309276/75416734-1dd31680-596a-11ea-9925-9596e054d05d.png)
Thanks.

**Comment by froeba** [comment]
That makes sense.  Getting that kind of access shouldn't even happen for most people that aren't already in ArmMbed organisation.  Thanks for reporting!  I'm going to close as there is nothing more for me to do.
